all: out/01 out/02 out/03 out/04 out/10

out/01: 01.c
	gcc -o ./out/01 01.c

out/02: 02.c
	gcc -o ./out/02 02.c

out/03: 03.c
	gcc -o ./out/03 03.c

out/04: 04.c
	gcc -o ./out/04 04.c

out/10: 10.c
	gcc -o ./out/10 10.c

.Phony: clean

clean: 
	rm -rf out/*
